baseURL = "https://morganericsson.github.io/msengcs/"
languageCode = "en-us"
title = "Civilingenjör i mjukvaruteknik"
theme = "hyde"
publishDir = "docs"

[params]
	description = "Ett utbildningskoncept under utveckling vid Linnéuniversitetet. Kontakt: morgan.ericsson@lnu.se"

[[menu.main]]
    name = "Kursplaner"
    identifier = "kp"
    url = "/descs/"
    pre = "Kursplaner"

[[menu.main]]
    name = "Utbildningsplan"
    identifier = "up"
    url = "/utbplan/"


[taxonomies]
	subject = "Subjects"